services:
  - type: web
    name: expense-tracker-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
